// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6OpRQeque-Zm5zFd9w8vEDbpY8HKoIrE',
    appId: '1:231745848498:web:df2ef0cf2b48774e26f5ab',
    messagingSenderId: '231745848498',
    projectId: 'flutter-firebase-bloc-crud',
    authDomain: 'flutter-firebase-bloc-crud.firebaseapp.com',
    storageBucket: 'flutter-firebase-bloc-crud.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjY8Z_dLozCMv8oQZGwg9R2qaBv0U325o',
    appId: '1:231745848498:android:fac2fd00b06d55f826f5ab',
    messagingSenderId: '231745848498',
    projectId: 'flutter-firebase-bloc-crud',
    storageBucket: 'flutter-firebase-bloc-crud.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtLfuXpuHhOhgmedq0o7pKa7PFyTCSQME',
    appId: '1:231745848498:ios:e6f5337a56f975c726f5ab',
    messagingSenderId: '231745848498',
    projectId: 'flutter-firebase-bloc-crud',
    storageBucket: 'flutter-firebase-bloc-crud.appspot.com',
    iosClientId: '231745848498-to6eo4javajb4shfskgngpemetoj6ha5.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterFirebaseBlocCrudApp',
  );
}
